name: Ownership Transfer
description: Transfer the ownership of a plugin
labels: [ "a:ownership-transfer" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Be mindful that we need to have the agreement of both parties to transfer the ownership.
        We also need to clearly assert the new owner is indeed related to the plugin in question.
  - type: input
    id: plugin-id
    attributes:
      label: Plugin ID
      description: |
        Tell us the plugin ID you wish to transfer the ownership.
    validations:
      required: true
  - type: input
    id: current-owner
    attributes:
      label: Current owner
      description: |
        Who is the current owner of the plugin? Link to the Gradle Plugin Portal profile.
    validations:
      required: true
  - type: input
    id: expected-owner
    attributes:
      label: Expected owner
      description: |
        Who is the expected owner of the plugin? Link to the Gradle Plugin Portal profile.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Why is the ownership transfer needed? Any relevant context about both parties.
        Providing context helps us confirm the legitimacy of the ownership transfer request.
    validations:
      required: true